### ISSUE TITLE
label_anything需要安装label-studio最新版

### ISSUE THREAD

**Issue by yIllusionSky** [open-mmlab/playground#121]
如标题，如果不安装最新版会出现这样的纹理：
![图片](https://github.com/open-mmlab/playground/assets/66589604/2deb8e02-3394-4743-bdfa-8d104e82fb76)

操作系统：Ubuntu22.04
GPU:6700xt
torch版本：Pytorch2.01 rocm

解决方案：
升级label-studio到最新版

**Comment by JimmyMa99** [comment]
我今天试了一下，跟label studio的版本无关，是因为你一开始没有load 进 sam的权重
请看下图，图1是ls旧版的，没有load权值，图2是同一个版本load了权值的，我猜你一开始第一次是没有成功load进权值
![9dc20da9a6391eb833bb3510e09c2a4](https://github.com/open-mmlab/playground/assets/101508488/779d4181-c3fd-4739-b52e-ce702da4c1ff)
![a932968f9b81e8a81a58e64966e79eb](https://github.com/open-mmlab/playground/assets/101508488/2486f7f3-6968-4ff1-ac66-03b9a87d1dee)

**Comment by Codegenius-Ai** [comment]
> 我今天试了一下，跟label studio的版本无关，是因为你一开始没有load 进 sam的权重 请看下图，图1是ls旧版的，没有load权值，图2是同一个版本load了权值的，我猜你一开始第一次是没有成功load进权值 ![9dc20da9a6391eb833bb3510e09c2a4](https://user-images.githubusercontent.com/101508488/252020193-779d4181-c3fd-4739-b52e-ce702da4c1ff.png) ![a932968f9b81e8a81a58e64966e79eb](https://user-images.githubusercontent.com/101508488/252020264-2486f7f3-6968-4ff1-ac66-03b9a87d1dee.png)

请问怎样load模型权重？
