### ISSUE TITLE
Label-Studio-SAM: How to use the trained model to label other image?

### ISSUE THREAD

**Issue by BOOSTMKII** [open-mmlab/playground#140]
There is a test_tracking.py file in tool, I also want to know how to use it (is it used on video?). Thank you very mcuh.

**Comment by JimmyMa99** [comment]
I noticed that label studio is able to annotate VIDEO OBJECT, see the link for the [official documentation](https://labelstud.io/blog/label-studio-1-6-video-object-tracking-and-new-annotation-ui/#new-video-object-tracking-functionality).
