### ISSUE TITLE
[label_anything]: Add model - Validation error

### ISSUE THREAD

**Issue by BOOSTMKII** [open-mmlab/playground#146]
<img width="569" alt="屏幕截图 2023-07-29 013520" src="https://github.com/open-mmlab/playground/assets/34444796/bf46e3bb-de1d-4c74-be8e-e2d357632568">
When I try to use the vit_h model, it said read timed out, although I set the ML_TIMEOUT_SETUP to 40.

<img width="569" alt="屏幕截图 2023-07-29 013721" src="https://github.com/open-mmlab/playground/assets/34444796/2ad81abf-ed4c-4d64-993b-a9d57c9dc586">
When I try to use hq sam models, also failed.

Anaconda prompt:
127.0.0.1 - - [26/Apr/2023 17:11:02] "POST /setup HTTP/1.1" 500 -

**Comment by BOOSTMKII** [comment]
关于vit_h模型，打开label studio时不能使用anaconda powershell prompt， 会使set ML_TIMEOUT_SETUP=40
命令失效，必须使用anaconda prompt。

**Comment by JimmyMa99** [comment]
> 关于vit_h模型，打开label studio时不能使用anaconda powershell prompt， 会使set ML_TIMEOUT_SETUP=40 命令失效，必须使用anaconda prompt。

请问这是已经解决了吗？

**Comment by BOOSTMKII** [comment]
> > 关于vit_h模型，打开label studio时不能使用anaconda powershell prompt， 会使set ML_TIMEOUT_SETUP=40 命令失效，必须使用anaconda prompt。
> 
> 请问这是已经解决了吗？

我解决了vit_h的问题，但是仍然不知道如何使用hq sam模型，不过或许vit_h已经足够，需要把提问关闭吗

**Comment by JimmyMa99** [comment]
> > > 关于vit_h模型，打开label studio时不能使用anaconda powershell prompt， 会使set ML_TIMEOUT_SETUP=40 命令失效，必须使用anaconda prompt。
> > 
> > 
> > 请问这是已经解决了吗？
> 
> 我解决了vit_h的问题，但是仍然不知道如何使用hq sam模型，不过或许vit_h已经足够，需要把提问关闭吗

关于hq_sam
其实只是换了个权重，你可以看看昨天merge的更新了readme，附带了下载链接，只需在启动后端时修改几个参数即可。
如果问题已经解决的话，也、可以close掉问题
