### ISSUE TITLE
some problems about mmtrack and mmdet

### ISSUE THREAD

**Issue by yahooo-mds** [open-mmlab/playground#46]
The code of from mmdet.models.tracks import ByteTrack may be wrong? when i change it to from mmtrack, it raise a error between mmcv2.0 and mmtrack---"AssertionError: MMCV==2.0.0 is used but incompatible. Please install mmcv>=1.3.17, <2.0.0.". i want some help.

**Comment by hhaAndroid** [comment]
@yahooo-mds Please follow our readme, mmtracking will be merged into mmdet later

**Comment by yahooo-mds** [comment]
Thanks, I have solved this.

**Comment by qingchunlizhi** [comment]
![image](https://github.com/open-mmlab/playground/assets/18531375/ad290b55-3b23-4902-a7c9-cf550a8af2f9)
I also encountered this problem with mmcv==2.0.0, mmdet==3.0.0rc6，too！How can I fix this bug?
