### ISSUE TITLE
Thanks for your wonderful work! Can you please share coco_cls_name.txt file?

### ISSUE THREAD

**Issue by aixiaodewugege** [open-mmlab/playground#47]
I want to use Grounding DINO generating all the bbox it can recognize and use SAM on it.

I think I probably can use coco_cls_name.txt. Can you please share how to generate or download it? Because I don't sure whether . should be include in txt file class name.

Thanks.

**Comment by hhaAndroid** [comment]
@aixiaodewugege It's already in the code base
