### ISSUE TITLE
Encountered some issues regarding implementing mmdet_ SAM and MMdet models+SAM

### ISSUE THREAD

**Issue by cunning2017** [open-mmlab/playground#48]
There is no problem running Faster R-CNN models, but running the dino model reported an error

**Comment by cunning2017** [comment]
![image](https://user-images.githubusercontent.com/56642800/233634865-8a787a5e-b256-4cae-83bd-4b37dbdb9868.png)

**Comment by cunning2017** [comment]
It feels like Roi was used in Dino_ Head, but the author is not registered in config

**Comment by cunning2017** [comment]
Has anyone implemented this model? Let's talk about it

**Comment by hhaAndroid** [comment]
@cunning2017 Okay, we'll test it and fix

**Comment by xin-li-67** [comment]
I did a quick fix on this, would you like to try it like this https://github.com/open-mmlab/playground/pull/50?

**Comment by cunning2017** [comment]
@xin-li-67 What do you mean by that?

**Comment by ranpin** [comment]
i meet the same error that There is no problem running Faster R-CNN models, but running the dino model reported an error.
![image](https://user-images.githubusercontent.com/51260021/233840603-65760fc3-579d-417b-b378-164aebbbc6e8.png)

**Comment by xin-li-67** [comment]
> i meet the same error that There is no problem running Faster R-CNN models, but running the dino model reported an error. ![image](https://user-images.githubusercontent.com/51260021/233840603-65760fc3-579d-417b-b378-164aebbbc6e8.png)

Yes, you can try the modification I did in #50.

**Comment by ranpin** [comment]
> > i meet the same error that There is no problem running Faster R-CNN models, but running the dino model reported an error. ![image](https://user-images.githubusercontent.com/51260021/233840603-65760fc3-579d-417b-b378-164aebbbc6e8.png)
> 
> Yes, you can try the modification I did in #50.

i don't know what you mean. can you explain more clearly please?  how can i modify the fllowing code?
![image](https://user-images.githubusercontent.com/51260021/233841582-ec56413e-1f45-4767-add0-b0cc609a2ef9.png)

**Comment by ranpin** [comment]
> > i meet the same error that There is no problem running Faster R-CNN models, but running the dino model reported an error. ![image](https://user-images.githubusercontent.com/51260021/233840603-65760fc3-579d-417b-b378-164aebbbc6e8.png)
> 
> Yes, you can try the modification I did in #50.

yes,it's work now. thank you!

**Comment by cunning2017** [comment]
@xin-li-67 What should I do?

**Comment by hhaAndroid** [comment]
https://github.com/open-mmlab/playground/pull/50
