### ISSUE TITLE
any plan with fully automated labeling?

### ISSUE THREAD

**Issue by ranpin** [open-mmlab/playground#53]
I see that you have introduced semi-automatic annotation, thank you for your work, but this is still rather laborious. Is it possible to combine this with the previously introduced mmdet-sam to automatically perform detection segmentation to get the annotation? 

In this case, we only need to specify the data folder to be processed and the category.txt to be detected for segmentation. then run the code to output directly to get the annotation file in coco etc. I would appreciate if you have any plans for this.

**Comment by vansin** [comment]
doing
