### ISSUE TITLE
I have this problem.

### ISSUE THREAD

**Issue by threeneedone** [open-mmlab/playground#57]
Traceback (most recent call last):
  File ".\play_controlnet_animation_sam.py", line 6, in <module>
    from mmedit.edit import MMEdit
ModuleNotFoundError: No module named 'mmedit'

Using mim install mmedit, python install mmedit cannot be solved.

**Comment by ly015** [comment]
Could you please verify the installation of mmedit by `pip show mmedit`?

**Comment by threeneedone** [comment]
> Could you please verify the installation of mmedit by `pip show mmedit`?

> pip show mmedit
WARNING: Package(s) not found: mmedit
>

like this.
