### ISSUE TITLE
[Feature Request] Label Anything

### ISSUE THREAD

**Issue by vansin** [open-mmlab/playground#58]
If you have any suggestions for Label Anything, you can leave a message here.

**Comment by vansin** [comment]
![image](https://user-images.githubusercontent.com/25839884/234454779-01c0b9d6-8de1-4da2-a271-1cd07209753c.png)

**Comment by vansin** [comment]
![image](https://user-images.githubusercontent.com/25839884/234454829-eab305fd-f688-4ab2-bc2a-490871f0accc.png)

**Comment by liuyongkang1-tal** [comment]
> ![image](https://user-images.githubusercontent.com/25839884/234454829-eab305fd-f688-4ab2-bc2a-490871f0accc.png)

能合并框和mask标签吗

**Comment by ZhangYuef** [comment]
Too much memory occupation when running SAM on cpu and it even will cause system crash. It's better to use ONNX.
