### ISSUE TITLE
[label_anything]: Add model - Validation error

### ISSUE THREAD

**Issue by puxiao** [open-mmlab/playground#60]
Window10 简体中文 64位 系统

Successfully connected to http://127.0.0.1:8003 but it doesn't look like a valid ML backend. Reason: 500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:8003/setup.
Check the ML backend server console logs to check the status. There might be
something wrong with your model or it might be incompatible with the current labeling configuration.
Version: 1.7.3

http://localhost:8003/
> {"model_dir":"E:\\python\\playground\\label_anything\\sam","status":"UP","v2":false}

http://127.0.0.1:8003/setup
> Method Not Allowed   The method is not allowed for the requested URL.

Anaconda prompt:
127.0.0.1 - - [26/Apr/2023 17:11:02] "POST /setup HTTP/1.1" 500 -

**??? why?**

**Comment by beyoursel** [comment]
首先得在setting里面的labeling interface定义所需标注的类别，然后才能导入Machine Leaning里面的模型

**Comment by puxiao** [comment]
labeling interface  我已经照着文档设置过了。
去添加模型后，去检测，我访问 http://127.0.0.1:8003/setup 网页显示：Method Not Allowed The method is not allowed for the requested URL.

**Comment by beyoursel** [comment]
您的邮件已收到，我会尽快阅读！

**Comment by beyoursel** [comment]
> labeling interface 我已经照着文档设置过了。 去添加模型后，去检测，我访问 http://127.0.0.1:8003/setup 网页显示：Method Not Allowed The method is not allowed for the requested URL.

我是在服务器上跑的，然后映射到本地打开，倒是没遇到你这个错误

**Comment by panp4n** [comment]
同样的问题

**Comment by JimmyMa99** [comment]
可能是因为使用vit-h，需要设置一下环境变量，具体已经在文档中更新

**Comment by puxiao** [comment]
果然没有问题了，感谢！

**Comment by liuyongkang1-tal** [comment]
同样的问题，设置了环境变量也没有解决

**Comment by JimmyMa99** [comment]
> 同样的问题，设置了环境变量也没有解决

请问sam推理后端保持开启了吗？

**Comment by liuyongkang1-tal** [comment]
开启了

**Comment by liuyongkang1-tal** [comment]
> > 同样的问题，设置了环境变量也没有解决
> 
> 请问sam推理后端保持开启了吗？

开启了的

**Comment by liuyongkang1-tal** [comment]
> > 同样的问题，设置了环境变量也没有解决
> 
> 请问sam推理后端保持开启了吗？

但我发现，GPU没有显存占用，感觉没起来似的

**Comment by JimmyMa99** [comment]
> > > 同样的问题，设置了环境变量也没有解决
> > 
> > 请问sam推理后端保持开启了吗？
> 
> 但我发现，GPU没有显存占用，感觉没起来似的

可能需要稍微等待模型的加载，另外请检查一下，看看是否出现报错的情况

**Comment by liuyongkang1-tal** [comment]
没看到报错
----&nbsp;原始邮件&nbsp;----
***@***.***&gt;;
Date:2023年4月28日(星期五)&nbsp;下午2:59
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:Re:&nbsp;[open-mmlab/playground]&nbsp;[label_anything]:&nbsp;Add&nbsp;model&nbsp;-&nbsp;Validation&nbsp;error&nbsp;(Issue&nbsp;#60)



    
同样的问题，设置了环境变量也没有解决
  
请问sam推理后端保持开启了吗？
  
但我发现，GPU没有显存占用，感觉没起来似的
  
可能需要稍微等待模型的加载，另外请检查一下，看看是否出现报错的情况
 
&mdash;

**Comment by JimmyMa99** [comment]
> 我再看下啊
> ----&nbsp;原始邮件&nbsp;----
> ***@***.***&gt;;
> Date:2023年4月28日(星期五)&nbsp;下午2:59
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> Subject:Re:&nbsp;[open-mmlab/playground]&nbsp;[label_anything]:&nbsp;Add&nbsp;model&nbsp;-&nbsp;Validation&nbsp;error&nbsp;(Issue&nbsp;#60)
> 
> 
> 
>     
> 同样的问题，设置了环境变量也没有解决
>   
> 请问sam推理后端保持开启了吗？
>   
> 但我发现，GPU没有显存占用，感觉没起来似的
>   
> 可能需要稍微等待模型的加载，另外请检查一下，看看是否出现报错的情况
>  
> &mdash;
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

可能需要检查一下你的URL填写是否和sam后端推理的ip端口一致

**Comment by BOOSTMKII** [comment]
我也遇到了相同的问题。尝试多次也没有办法，只能使用vit_b，vit_h和hq模型都用不了，请问您最后是如何修改环境变量让问题得以解决的？谢谢！

**Comment by JimmyMa99** [comment]
> 我也遇到了相同的问题。尝试多次也没有办法，只能使用vit_b，vit_h和hq模型都用不了，请问您最后是如何修改环境变量让问题得以解决的？谢谢！

你好，关于环境变量的设置可以看以下：

```
# Linux requires the following commands
export ML_TIMEOUT_SETUP=40
# Windows requires the following commands
set ML_TIMEOUT_SETUP=40
```

但是需要注意的是，硬件参数也对模型的导入有影响，我测试的时候使用的是24G显存的3090，或者只使用CPU进行推理，希望这些参数对解决您的问题有所帮助。

**Comment by BOOSTMKII** [comment]
> > 我也遇到了相同的问题。尝试多次也没有办法，只能使用vit_b，vit_h和hq模型都用不了，请问您最后是如何修改环境变量让问题得以解决的？谢谢！
> 
> 你好，关于环境变量的设置可以看以下：
> 
> ```
> # Linux requires the following commands
> export ML_TIMEOUT_SETUP=40
> # Windows requires the following commands
> set ML_TIMEOUT_SETUP=40
> ```
> 
> 但是需要注意的是，硬件参数也对模型的导入有影响，我测试的时候使用的是24G显存的3090，或者只使用CPU进行推理，希望这些参数对解决您的问题有所帮助。

谢谢，不过这个设置我跟随文档操作时已经做过了，错误信息还是显示read timed out=3.0（是在第二个打开label studio的终端中设置吗？不过我三种可能都尝试过了）。具体图片我在新提问中有贴，我使用的是48G3090，或者我试试CPU吧。

**Comment by BOOSTMKII** [comment]
> > 我也遇到了相同的问题。尝试多次也没有办法，只能使用vit_b，vit_h和hq模型都用不了，请问您最后是如何修改环境变量让问题得以解决的？谢谢！
> 
> 你好，关于环境变量的设置可以看以下：
> 
> ```
> # Linux requires the following commands
> export ML_TIMEOUT_SETUP=40
> # Windows requires the following commands
> set ML_TIMEOUT_SETUP=40
> ```
> 
> 但是需要注意的是，硬件参数也对模型的导入有影响，我测试的时候使用的是24G显存的3090，或者只使用CPU进行推理，希望这些参数对解决您的问题有所帮助。

您好，我发现了原因所在。关于vit_h模型，我原先打开label studio时使用的是anaconda powershell prompt，似乎set ML_TIMEOUT_SETUP=40命令没有作用，当我换成anaconda prompt时，就可以运行了。
