### ISSUE TITLE
点开网页出现错误

### ISSUE THREAD

**Issue by I-am-zxf** [open-mmlab/playground#68]
{"model_dir":"d:\\playground\\label_anything\\sam","status":"UP","v2":false}

**Comment by JimmyMa99** [comment]
你好，你打开的应该是SAM后端推理，请根据label studio 提示打开可视化页面
![image](https://user-images.githubusercontent.com/101508488/235238679-e2348d0b-2ccf-404e-ae6b-31d890bd3518.png)
