### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by EricGotU** [open-mmlab/playground#79]
全程按照文档操作，在add model -> validate and save时，显示validation error：
![图片](https://user-images.githubusercontent.com/93647469/236145825-913cef9e-ee6f-42ec-88be-e278fc8d4779.png)

同时，SAM后端cmd中报错信息如下：
![图片](https://user-images.githubusercontent.com/93647469/236146937-b454ec4c-e084-4b2a-b7e5-3803d315bcea.png)

**Comment by fycatfan** [comment]
I have the same problem.
![image](https://user-images.githubusercontent.com/20541506/236162887-93eb4616-9e74-4046-bc40-7242c8fdb260.png)

**Comment by PtttCode** [comment]
you should add **KeyPointLabels** tag in your project setting:
`
<KeyPointLabels name="KeyPointLabels" toName="image">
    <Label value="cat" smart="true" background="#e51515" showInline="true"/>
    <Label value="person" smart="true" background="#412cdd" showInline="true"/>
</KeyPointLabels>
`


![image](https://user-images.githubusercontent.com/36265886/236599683-9ac07a1e-c41f-4c1c-853c-d94c07f723b7.png)

**Comment by EricGotU** [comment]
> you should add **KeyPointLabels** tag in your project setting:
> 
> ```
> 
> <KeyPointLabels name="KeyPointLabels" toName="image">
>     <Label value="cat" smart="true" background="#e51515" showInline="true"/>
>     <Label value="person" smart="true" background="#412cdd" showInline="true"/>
> </KeyPointLabels>
> ```
> 
> ![image](https://user-images.githubusercontent.com/36265886/236599683-9ac07a1e-c41f-4c1c-853c-d94c07f723b7.png)

Thanks for ur reply. It does work!
